// svelte/src/lib/components/ChatAdminEdit.svelte
<script lang="ts">
  import Avatar from './Avatar.svelte';
  import {
    checkAdminUsername,
    deleteChat,
    leaveChat,
    makeChatPrivate,
    makeChatPublic,
    removeChatPhoto,
    saveChatAbout,
    saveChatPhoto,
    saveChatTitle,
    setForumEnabled,
    setSignaturesEnabled,
    type AdminChat
  } from '$lib/telegram/admin';

  let {
    chat,
    onchanged,
    onmigrated,
    onleft
  }: {
    chat: AdminChat;
    onchanged: () => void;
    onmigrated: (peerId: number) => void;
    /** The chat is gone — the panel should close. */
    onleft: () => void;
  } = $props();

  let title = $state(chat.title);
  let about = $state(chat.about);
  let busy = $state(false);
  let error = $state('');
  let status = $state('');

  // Toggles are optimistic and roll back on failure, the way Settings does it.
  let forum = $state(chat.isForum);
  let signatures = $state(chat.signaturesEnabled);

  let photoInput = $state<HTMLInputElement | null>(null);

  let isPublic = $state(!!chat.username);
  let link = $state(chat.username);
  let linkFree = $state<boolean | null>(null);
  let linkError = $state('');
  let linkTimer: ReturnType<typeof setTimeout> | undefined;

  let dirty = $derived(title.trim() !== chat.title || about.trim() !== chat.about);
  let canSave = $derived(dirty && title.trim().length > 0 && !busy);

  const kind = $derived(chat.isChannel ? 'channel' : 'group');

  function fail(err: any, fallback: string) {
    error = err?.type || err?.message || fallback;
  }

  function flash(message: string) {
    status = message;
    setTimeout(() => (status = ''), 2500);
  }

  async function save() {
    if (!canSave) return;
    busy = true;
    error = '';

    try {
      if (title.trim() !== chat.title) await saveChatTitle(chat.peerId, title);
      if (about.trim() !== chat.about) await saveChatAbout(chat.peerId, about);
      flash('Saved');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to save');
    } finally {
      busy = false;
    }
  }

  async function onPhotoPicked(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    // Clear it straight away so picking the same file twice still fires.
    input.value = '';
    if (!file) return;

    busy = true;
    error = '';
    try {
      await saveChatPhoto(chat.peerId, file);
      flash('Photo updated');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to upload the photo');
    } finally {
      busy = false;
    }
  }

  async function dropPhoto() {
    busy = true;
    error = '';
    try {
      await removeChatPhoto(chat.peerId);
      flash('Photo removed');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to remove the photo');
    } finally {
      busy = false;
    }
  }

  function onLinkInput() {
    clearTimeout(linkTimer);
    linkError = '';
    linkFree = null;
    const wanted = link.trim().replace(/^@/, '');
    if (wanted.length < 5 || wanted === chat.username) return;

    linkTimer = setTimeout(async () => {
      try {
        const free = await checkAdminUsername(chat.peerId, wanted);
        // The field may have moved on while the check was in flight.
        if (link.trim().replace(/^@/, '') === wanted) linkFree = free;
      } catch (err: any) {
        if (link.trim().replace(/^@/, '') === wanted) {
          linkFree = false;
          linkError = err?.type || err?.message || 'That link cannot be used';
        }
      }
    }, 400);
  }

  async function applyType() {
    if (busy) return;
    busy = true;
    error = '';
    linkError = '';

    try {
      if (isPublic) {
        const newPeerId = await makeChatPublic(chat.peerId, link);
        // A basic group is migrated to a supergroup to get a link at all, which
        // moves it to a different peer — the old one stops receiving messages.
        if (newPeerId !== chat.peerId) {
          onmigrated(newPeerId);
          return;
        }
      } else {
        await makeChatPrivate(chat.peerId);
      }

      flash('Saved');
      onchanged();
    } catch (err: any) {
      linkError = err?.type || err?.message || 'Failed to change the chat type';
    } finally {
      busy = false;
    }
  }

  async function toggleForum() {
    const next = !forum;
    forum = next;
    try {
      await setForumEnabled(chat.peerId, next);
      onchanged();
    } catch (err: any) {
      forum = !next;
      fail(err, 'Failed to change topics');
    }
  }

  async function toggleSignatures() {
    const next = !signatures;
    signatures = next;
    try {
      await setSignaturesEnabled(chat.peerId, next);
      onchanged();
    } catch (err: any) {
      signatures = !next;
      fail(err, 'Failed to change signatures');
    }
  }

  async function destroy() {
    if (!confirm(`Delete this ${kind} for everyone? This cannot be undone.`)) return;
    busy = true;
    error = '';
    try {
      await deleteChat(chat.peerId);
      onleft();
    } catch (err: any) {
      fail(err, 'Failed to delete');
      busy = false;
    }
  }

  async function leave() {
    if (!confirm(`Leave this ${kind}?`)) return;
    busy = true;
    error = '';
    try {
      await leaveChat(chat.peerId);
      onleft();
    } catch (err: any) {
      fail(err, 'Failed to leave');
      busy = false;
    }
  }
</script>

<div class="pane">
  {#if chat.access.changeInfo}
    <div class="photo-row">
      <Avatar peerId={chat.peerId} title={chat.title} size={64} />
      <div class="photo-actions">
        <button class="admin-btn" onclick={() => photoInput?.click()} disabled={busy}>
          Upload photo
        </button>
        <button class="admin-btn danger" onclick={dropPhoto} disabled={busy}>Remove</button>
      </div>
      <input
        class="picker"
        type="file"
        accept="image/*"
        bind:this={photoInput}
        onchange={onPhotoPicked}
      />
    </div>

    <label class="admin-field">
      <span>Name</span>
      <input bind:value={title} maxlength="128" />
    </label>

    <label class="admin-field">
      <span>Description</span>
      <textarea bind:value={about} maxlength="255" rows="3"></textarea>
    </label>

    <div class="admin-actions">
      <button class="admin-btn primary" onclick={save} disabled={!canSave}>
        {busy ? 'Saving…' : 'Save'}
      </button>
    </div>
  {/if}

  {#if chat.access.changeType}
    <section>
      <p class="admin-label">{chat.isChannel ? 'Channel type' : 'Group type'}</p>
      <div class="kinds">
        <button class:on={isPublic} onclick={() => (isPublic = true)}>Public</button>
        <button class:on={!isPublic} onclick={() => (isPublic = false)}>Private</button>
      </div>

      {#if isPublic}
        <div class="link-edit">
          <span class="at">@</span>
          <input
            bind:value={link}
            oninput={onLinkInput}
            placeholder="link"
            maxlength="32"
            spellcheck="false"
            autocapitalize="none"
          />
        </div>
        {#if linkFree === true}
          <p class="admin-ok">@{link.trim().replace(/^@/, '')} is available</p>
        {/if}
        {#if chat.isBasicGroup}
          <p class="admin-hint">A public group becomes a supergroup.</p>
        {/if}
      {:else}
        <p class="admin-hint">
          Only people with an invite link can join a private {kind}.
        </p>
      {/if}
      {#if linkError}<p class="admin-error">{linkError}</p>{/if}

      <div class="admin-actions">
        <button
          class="admin-btn primary"
          onclick={applyType}
          disabled={busy || (isPublic && link.trim().replace(/^@/, '').length < 5)}
        >
          {busy ? 'Saving…' : 'Apply'}
        </button>
      </div>
    </section>
  {/if}

  {#if chat.access.changeInfo && !chat.isChannel}
    <section>
      <label class="admin-toggle">
        <input type="checkbox" checked={forum} onchange={toggleForum} disabled={busy} />
        <span>Topics</span>
      </label>
      <p class="admin-hint">Split the group's history into separate topics.</p>
    </section>
  {/if}

  {#if chat.access.changeInfo && chat.isChannel}
    <section>
      <label class="admin-toggle">
        <input type="checkbox" checked={signatures} onchange={toggleSignatures} disabled={busy} />
        <span>Sign messages</span>
      </label>
      <p class="admin-hint">Show the author's name under each post.</p>
    </section>
  {/if}

  <section>
    <p class="admin-label">Danger zone</p>
    <div class="admin-actions left">
      <button class="admin-btn danger" onclick={leave} disabled={busy}>Leave {kind}</button>
      {#if chat.access.deleteChat}
        <button class="admin-btn danger" onclick={destroy} disabled={busy}>Delete {kind}</button>
      {/if}
    </div>
  </section>

  {#if error}<p class="admin-error">{error}</p>{/if}
  {#if status}<p class="admin-ok">{status}</p>{/if}
</div>

<style>
  .pane {
    display: grid;
    gap: 12px;
  }

  section {
    display: grid;
    gap: 6px;
    padding-top: 12px;
    border-top: 1px solid var(--border);
  }

  .photo-row {
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .photo-actions {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }

  .picker {
    display: none;
  }

  .kinds {
    display: flex;
    gap: 8px;
  }

  .kinds button {
    flex: 1;
    padding: 7px 12px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: var(--text-dim);
    cursor: pointer;
    font-size: 13px;
  }

  .kinds button.on {
    border-color: var(--accent);
    color: var(--accent);
  }

  .link-edit {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 10px;
  }

  .link-edit:focus-within {
    border-color: var(--accent);
  }

  .at {
    color: var(--text-dim);
  }

  .link-edit input {
    flex: 1;
    min-width: 0;
    background: none;
    border: none;
    color: inherit;
    font: inherit;
    outline: none;
  }
</style>

// astro/src/components/ChatAdminEdit.tsx
/*
 * Ported from svelte/src/lib/components/ChatAdminEdit.svelte.
 *
 * Three porting notes:
 *  - `dirty`, `canSave` and `kind` were `$derived` over props, so they stay plain
 *    `const`s recomputed on each render — a `useComputed` only tracks signal reads
 *    and would never see `chat` change (CONVERSION.md §4). Reading `title.value`
 *    and friends while rendering them is what re-renders the pane;
 *  - `linkTimer` was a plain `let` in the Svelte body, which runs once per
 *    instance; a Preact body runs on every render, so the timer handle lives in a
 *    `useRef` and keeps its identity across passes;
 *  - the link field was `bind:value` *plus* `oninput`, and `onLinkInput` reads the
 *    new value — so the signal is written before the handler is called.
 */
import {useRef} from 'preact/hooks';
import {useSignal} from '@preact/signals';

import {Avatar} from './Avatar';
import {
  checkAdminUsername,
  deleteChat,
  leaveChat,
  makeChatPrivate,
  makeChatPublic,
  removeChatPhoto,
  saveChatAbout,
  saveChatPhoto,
  saveChatTitle,
  setForumEnabled,
  setSignaturesEnabled,
  type AdminChat
} from '$lib/telegram/admin';

import './ChatAdminEdit.css';

interface Props {
  chat: AdminChat;
  onchanged: () => void;
  onmigrated: (peerId: number) => void;
  /** The chat is gone — the panel should close. */
  onleft: () => void;
}

export function ChatAdminEdit({chat, onchanged, onmigrated, onleft}: Props) {
  const title = useSignal(chat.title);
  const about = useSignal(chat.about);
  const busy = useSignal(false);
  const error = useSignal('');
  const status = useSignal('');

  // Toggles are optimistic and roll back on failure, the way Settings does it.
  const forum = useSignal(chat.isForum);
  const signatures = useSignal(chat.signaturesEnabled);

  const photoInput = useRef<HTMLInputElement>(null);

  const isPublic = useSignal(!!chat.username);
  const link = useSignal(chat.username);
  const linkFree = useSignal<boolean | null>(null);
  const linkError = useSignal('');
  const linkTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  const dirty = title.value.trim() !== chat.title || about.value.trim() !== chat.about;
  const canSave = dirty && title.value.trim().length > 0 && !busy.value;

  const kind = chat.isChannel ? 'channel' : 'group';

  function fail(err: any, fallback: string) {
    error.value = err?.type || err?.message || fallback;
  }

  function flash(message: string) {
    status.value = message;
    setTimeout(() => (status.value = ''), 2500);
  }

  async function save() {
    if (!canSave) return;
    busy.value = true;
    error.value = '';

    try {
      if (title.value.trim() !== chat.title) await saveChatTitle(chat.peerId, title.value);
      if (about.value.trim() !== chat.about) await saveChatAbout(chat.peerId, about.value);
      flash('Saved');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to save');
    } finally {
      busy.value = false;
    }
  }

  async function onPhotoPicked(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    // Clear it straight away so picking the same file twice still fires.
    input.value = '';
    if (!file) return;

    busy.value = true;
    error.value = '';
    try {
      await saveChatPhoto(chat.peerId, file);
      flash('Photo updated');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to upload the photo');
    } finally {
      busy.value = false;
    }
  }

  async function dropPhoto() {
    busy.value = true;
    error.value = '';
    try {
      await removeChatPhoto(chat.peerId);
      flash('Photo removed');
      onchanged();
    } catch (err: any) {
      fail(err, 'Failed to remove the photo');
    } finally {
      busy.value = false;
    }
  }

  function onLinkInput() {
    clearTimeout(linkTimer.current);
    linkError.value = '';
    linkFree.value = null;
    const wanted = link.value.trim().replace(/^@/, '');
    if (wanted.length < 5 || wanted === chat.username) return;

    linkTimer.current = setTimeout(async () => {
      try {
        const free = await checkAdminUsername(chat.peerId, wanted);
        // The field may have moved on while the check was in flight.
        if (link.value.trim().replace(/^@/, '') === wanted) linkFree.value = free;
      } catch (err: any) {
        if (link.value.trim().replace(/^@/, '') === wanted) {
          linkFree.value = false;
          linkError.value = err?.type || err?.message || 'That link cannot be used';
        }
      }
    }, 400);
  }

  async function applyType() {
    if (busy.value) return;
    busy.value = true;
    error.value = '';
    linkError.value = '';

    try {
      if (isPublic.value) {
        const newPeerId = await makeChatPublic(chat.peerId, link.value);
        // A basic group is migrated to a supergroup to get a link at all, which
        // moves it to a different peer — the old one stops receiving messages.
        if (newPeerId !== chat.peerId) {
          onmigrated(newPeerId);
          return;
        }
      } else {
        await makeChatPrivate(chat.peerId);
      }

      flash('Saved');
      onchanged();
    } catch (err: any) {
      linkError.value = err?.type || err?.message || 'Failed to change the chat type';
    } finally {
      busy.value = false;
    }
  }

  async function toggleForum() {
    const next = !forum.value;
    forum.value = next;
    try {
      await setForumEnabled(chat.peerId, next);
      onchanged();
    } catch (err: any) {
      forum.value = !next;
      fail(err, 'Failed to change topics');
    }
  }

  async function toggleSignatures() {
    const next = !signatures.value;
    signatures.value = next;
    try {
      await setSignaturesEnabled(chat.peerId, next);
      onchanged();
    } catch (err: any) {
      signatures.value = !next;
      fail(err, 'Failed to change signatures');
    }
  }

  async function destroy() {
    if (!confirm(`Delete this ${kind} for everyone? This cannot be undone.`)) return;
    busy.value = true;
    error.value = '';
    try {
      await deleteChat(chat.peerId);
      onleft();
    } catch (err: any) {
      fail(err, 'Failed to delete');
      busy.value = false;
    }
  }

  async function leave() {
    if (!confirm(`Leave this ${kind}?`)) return;
    busy.value = true;
    error.value = '';
    try {
      await leaveChat(chat.peerId);
      onleft();
    } catch (err: any) {
      fail(err, 'Failed to leave');
      busy.value = false;
    }
  }

  return (
    <div class="pane">
      {chat.access.changeInfo && (
        <>
          <div class="photo-row">
            <Avatar peerId={chat.peerId} title={chat.title} size={64} />
            <div class="photo-actions">
              <button class="admin-btn" onClick={() => photoInput.current?.click()} disabled={busy.value}>
                Upload photo
              </button>
              <button class="admin-btn danger" onClick={dropPhoto} disabled={busy.value}>Remove</button>
            </div>
            <input
              class="picker"
              type="file"
              accept="image/*"
              ref={photoInput}
              onChange={onPhotoPicked}
            />
          </div>

          <label class="admin-field">
            <span>Name</span>
            <input
              value={title.value}
              onInput={(e) => (title.value = (e.target as HTMLInputElement).value)}
              maxlength={128}
            />
          </label>

          <label class="admin-field">
            <span>Description</span>
            <textarea
              value={about.value}
              onInput={(e) => (about.value = (e.target as HTMLTextAreaElement).value)}
              maxlength={255}
              rows={3}
            />
          </label>

          <div class="admin-actions">
            <button class="admin-btn primary" onClick={save} disabled={!canSave}>
              {busy.value ? 'Saving…' : 'Save'}
            </button>
          </div>
        </>
      )}

      {chat.access.changeType && (
        <section>
          <p class="admin-label">{chat.isChannel ? 'Channel type' : 'Group type'}</p>
          <div class="kinds">
            <button class={isPublic.value ? 'on' : ''} onClick={() => (isPublic.value = true)}>Public</button>
            <button class={!isPublic.value ? 'on' : ''} onClick={() => (isPublic.value = false)}>Private</button>
          </div>

          {isPublic.value ?
            <>
              <div class="link-edit">
                <span class="at">@</span>
                <input
                  value={link.value}
                  onInput={(e) => {
                    link.value = (e.target as HTMLInputElement).value;
                    onLinkInput();
                  }}
                  placeholder="link"
                  maxlength={32}
                  spellcheck={false}
                  autocapitalize="none"
                />
              </div>
              {linkFree.value === true && (
                <p class="admin-ok">@{link.value.trim().replace(/^@/, '')} is available</p>
              )}
              {chat.isBasicGroup && (
                <p class="admin-hint">A public group becomes a supergroup.</p>
              )}
            </> :
            <p class="admin-hint">
              Only people with an invite link can join a private {kind}.
            </p>}
          {linkError.value && <p class="admin-error">{linkError.value}</p>}

          <div class="admin-actions">
            <button
              class="admin-btn primary"
              onClick={applyType}
              disabled={busy.value || (isPublic.value && link.value.trim().replace(/^@/, '').length < 5)}
            >
              {busy.value ? 'Saving…' : 'Apply'}
            </button>
          </div>
        </section>
      )}

      {chat.access.changeInfo && !chat.isChannel && (
        <section>
          <label class="admin-toggle">
            <input type="checkbox" checked={forum.value} onChange={toggleForum} disabled={busy.value} />
            <span>Topics</span>
          </label>
          <p class="admin-hint">Split the group's history into separate topics.</p>
        </section>
      )}

      {chat.access.changeInfo && chat.isChannel && (
        <section>
          <label class="admin-toggle">
            <input type="checkbox" checked={signatures.value} onChange={toggleSignatures} disabled={busy.value} />
            <span>Sign messages</span>
          </label>
          <p class="admin-hint">Show the author's name under each post.</p>
        </section>
      )}

      <section>
        <p class="admin-label">Danger zone</p>
        <div class="admin-actions left">
          <button class="admin-btn danger" onClick={leave} disabled={busy.value}>Leave {kind}</button>
          {chat.access.deleteChat && (
            <button class="admin-btn danger" onClick={destroy} disabled={busy.value}>Delete {kind}</button>
          )}
        </div>
      </section>

      {error.value && <p class="admin-error">{error.value}</p>}
      {status.value && <p class="admin-ok">{status.value}</p>}
    </div>
  );
}
