// svelte/src/lib/components/NewChat.svelte
<script lang="ts">
  import Avatar from './Avatar.svelte';
  import {createChannel, createGroup, setChatUsername, type DialogItem} from '$lib/telegram/chats';

  let {
    dialogs,
    onclose,
    oncreated
  }: {
    dialogs: DialogItem[];
    onclose: () => void;
    oncreated: (peerId: number) => void;
  } = $props();

  let kind = $state<'group' | 'channel'>('group');
  let title = $state('');
  let about = $state('');
  let link = $state('');
  /**
   * Set once the chat exists. A failed @link must not create a second chat on
   * retry, so creation is skipped when this is filled in.
   */
  let createdPeerId = $state<number | null>(null);
  let query = $state('');
  let selected = $state<Set<number>>(new Set());
  let busy = $state(false);
  let error = $state('');

  // You cannot seed a chat with yourself, and only users can be invited.
  const contacts = $derived(dialogs.filter((d) => d.isUser && !d.isSelf));

  const filtered = $derived(
    query.trim()
      ? contacts.filter((d) => d.title.toLowerCase().includes(query.trim().toLowerCase()))
      : contacts
  );

  // A basic group must be created with at least one other member; a channel can
  // start empty and be filled later.
  const canCreate = $derived(
    !!title.trim() && (kind === 'channel' || selected.size > 0)
  );

  function toggle(peerId: number) {
    const next = new Set(selected);
    if (next.has(peerId)) next.delete(peerId);
    else next.add(peerId);
    selected = next;
  }

  async function create() {
    if (!canCreate || busy) return;
    busy = true;
    error = '';

    try {
      const members = [...selected];
      if (createdPeerId === null) {
        createdPeerId =
          kind === 'channel'
            ? await createChannel(title.trim(), about.trim(), members)
            : await createGroup(title.trim(), members);
      }

      let peerId = createdPeerId;
      if (link.trim()) peerId = await setChatUsername(peerId, link);

      oncreated(peerId);
    } catch (err: any) {
      error = err?.type || err?.message || 'Failed to create chat';
    } finally {
      busy = false;
    }
  }
</script>

<div class="backdrop" onclick={onclose} role="presentation">
  <div class="dialog" onclick={(e) => e.stopPropagation()} role="presentation">
    <header>New {kind}</header>

    <div class="kinds">
      <button class:on={kind === 'group'} onclick={() => (kind = 'group')}>Group</button>
      <button class:on={kind === 'channel'} onclick={() => (kind = 'channel')}>Channel</button>
    </div>

    <label class="field">
      <span>Name</span>
      <input bind:value={title} placeholder={kind === 'channel' ? 'Channel name' : 'Group name'} maxlength="128" />
    </label>

    {#if kind === 'channel'}
      <label class="field">
        <span>Description</span>
        <textarea bind:value={about} placeholder="Optional" maxlength="255" rows="2"></textarea>
      </label>
    {/if}

    <label class="field">
      <span>Public link</span>
      <span class="link-edit">
        <span class="at">@</span>
        <input
          bind:value={link}
          placeholder="Optional — leave empty for a private {kind}"
          maxlength="32"
          spellcheck="false"
          autocapitalize="none"
        />
      </span>
      {#if kind === 'group' && link.trim()}
        <span class="hint">A public group becomes a supergroup.</span>
      {/if}
    </label>

    <p class="label">
      Members ({selected.size})
      {#if kind === 'channel'}<span class="muted">— optional</span>{/if}
    </p>
    <input class="search" placeholder="Search contacts" bind:value={query} />

    <div class="list">
      {#each filtered as dialog (dialog.peerId)}
        <button class="row" class:on={selected.has(dialog.peerId)} onclick={() => toggle(dialog.peerId)}>
          <span class="check">{selected.has(dialog.peerId) ? '☑' : '☐'}</span>
          <Avatar peerId={dialog.peerId} title={dialog.title} size={32} />
          <span class="name">{dialog.title}</span>
        </button>
      {/each}
      {#if !filtered.length}<p class="muted">No contacts found.</p>{/if}
    </div>

    {#if error}<p class="error">{error}</p>{/if}
    {#if createdPeerId !== null && error}
      <p class="hint">The {kind} was created — only the link failed.</p>
    {/if}

    <footer>
      <span class="spacer"></span>
      {#if createdPeerId !== null}
        <button onclick={() => oncreated(createdPeerId!)} disabled={busy}>Open without link</button>
      {:else}
        <button onclick={onclose} disabled={busy}>Cancel</button>
      {/if}
      <button class="primary" onclick={create} disabled={busy || !canCreate}>
        {busy ? 'Creating…' : createdPeerId !== null ? 'Retry link' : 'Create'}
      </button>
    </footer>
  </div>
</div>

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.55);
    display: grid;
    place-items: center;
    z-index: 95;
  }

  .dialog {
    width: min(420px, calc(100vw - 32px));
    max-height: min(600px, calc(100vh - 48px));
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 18px;
    background: var(--bg-elevated);
    border: 1px solid var(--border);
    border-radius: 14px;
  }

  header {
    font-weight: 600;
    font-size: 17px;
    text-transform: capitalize;
  }

  .kinds {
    display: flex;
    gap: 8px;
  }

  .kinds button {
    flex: 1;
    padding: 8px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: inherit;
    cursor: pointer;
  }

  .kinds button.on {
    border-color: var(--accent);
    color: var(--accent);
  }

  .field {
    display: grid;
    gap: 4px;
    font-size: 13px;
    color: var(--text-dim);
  }

  input,
  textarea {
    padding: 9px 12px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: var(--text);
    font: inherit;
    outline: none;
    resize: none;
  }

  input:focus,
  textarea:focus {
    border-color: var(--accent);
  }

  .label {
    margin: 0;
    font-size: 13px;
    color: var(--text-dim);
  }

  .link-edit {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 0 10px;
    border: 1px solid var(--border);
    border-radius: 10px;
    color: var(--text);
  }

  .link-edit:focus-within {
    border-color: var(--accent);
  }

  .at {
    color: var(--text-dim);
  }

  .link-edit input {
    flex: 1;
    min-width: 0;
    padding: 9px 0;
    border: none;
    border-radius: 0;
  }

  .hint {
    font-size: 12px;
    color: var(--text-dim);
  }

  .list {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    border: 1px solid var(--border);
    border-radius: 10px;
  }

  .row {
    display: flex;
    align-items: center;
    gap: 10px;
    width: 100%;
    padding: 8px 10px;
    background: none;
    border: none;
    color: inherit;
    cursor: pointer;
    text-align: left;
  }

  .row:hover {
    background: color-mix(in srgb, var(--text) 6%, transparent);
  }

  .row.on .name {
    color: var(--accent);
  }

  .name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .muted {
    padding: 10px;
    margin: 0;
    color: var(--text-dim);
    font-size: 13px;
  }

  .error {
    margin: 0;
    color: var(--danger);
    font-size: 13px;
  }

  footer {
    display: flex;
    gap: 8px;
    align-items: center;
  }

  .spacer {
    flex: 1;
  }

  footer button {
    padding: 8px 14px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: inherit;
    cursor: pointer;
  }

  footer button.primary {
    background: var(--accent);
    border-color: var(--accent);
    color: #fff;
  }

  footer button:disabled {
    opacity: 0.5;
    cursor: default;
  }
</style>

// astro/src/components/NewChat.tsx
/*
 * Ported from svelte/src/lib/components/NewChat.svelte.
 *
 * `contacts` derives from the `dialogs` *prop*, so it is a `useMemo` keyed on
 * that prop rather than a `useComputed` — `useComputed` tracks signal reads and
 * would never see the prop change. `filtered` mixes both, so it re-computes on
 * the memoised list and on `query`, which sits in its dependency list.
 */
import {useMemo} from 'preact/hooks';
import {useComputed, useSignal} from '@preact/signals';

import {createChannel, createGroup, setChatUsername, type DialogItem} from '$lib/telegram/chats';

import {Avatar} from './Avatar';

import './NewChat.css';

interface Props {
  dialogs: DialogItem[];
  onclose: () => void;
  oncreated: (peerId: number) => void;
}

export function NewChat({dialogs, onclose, oncreated}: Props) {
  const kind = useSignal<'group' | 'channel'>('group');
  const title = useSignal('');
  const about = useSignal('');
  const link = useSignal('');
  /**
   * Set once the chat exists. A failed @link must not create a second chat on
   * retry, so creation is skipped when this is filled in.
   */
  const createdPeerId = useSignal<number | null>(null);
  const query = useSignal('');
  const selected = useSignal<Set<number>>(new Set());
  const busy = useSignal(false);
  const error = useSignal('');

  // You cannot seed a chat with yourself, and only users can be invited.
  const contacts = useMemo(() => dialogs.filter((d) => d.isUser && !d.isSelf), [dialogs]);

  const filtered = useMemo(
    () => query.value.trim()
      ? contacts.filter((d) => d.title.toLowerCase().includes(query.value.trim().toLowerCase()))
      : contacts,
    [contacts, query.value]
  );

  // A basic group must be created with at least one other member; a channel can
  // start empty and be filled later.
  const canCreate = useComputed(
    () => !!title.value.trim() && (kind.value === 'channel' || selected.value.size > 0)
  );

  function toggle(peerId: number) {
    const next = new Set(selected.value);
    if(next.has(peerId)) next.delete(peerId);
    else next.add(peerId);
    selected.value = next;
  }

  async function create() {
    if(!canCreate.value || busy.value) return;
    busy.value = true;
    error.value = '';

    try {
      const members = [...selected.value];
      if(createdPeerId.value === null) {
        createdPeerId.value =
          kind.value === 'channel'
            ? await createChannel(title.value.trim(), about.value.trim(), members)
            : await createGroup(title.value.trim(), members);
      }

      let peerId = createdPeerId.value;
      if(link.value.trim()) peerId = await setChatUsername(peerId, link.value);

      oncreated(peerId);
    } catch(err: any) {
      error.value = err?.type || err?.message || 'Failed to create chat';
    } finally {
      busy.value = false;
    }
  }

  return (
    <div class="backdrop" onClick={onclose} role="presentation">
      <div class="dialog" onClick={(e) => e.stopPropagation()} role="presentation">
        <header>New {kind.value}</header>

        <div class="kinds">
          <button class={kind.value === 'group' ? 'on' : ''} onClick={() => (kind.value = 'group')}>Group</button>
          <button class={kind.value === 'channel' ? 'on' : ''} onClick={() => (kind.value = 'channel')}>Channel</button>
        </div>

        <label class="field">
          <span>Name</span>
          <input
            value={title.value}
            onInput={(e) => (title.value = (e.target as HTMLInputElement).value)}
            placeholder={kind.value === 'channel' ? 'Channel name' : 'Group name'}
            maxlength={128}
          />
        </label>

        {kind.value === 'channel' &&
          <label class="field">
            <span>Description</span>
            <textarea
              value={about.value}
              onInput={(e) => (about.value = (e.target as HTMLTextAreaElement).value)}
              placeholder="Optional"
              maxlength={255}
              rows={2}
            ></textarea>
          </label>}

        <label class="field">
          <span>Public link</span>
          <span class="link-edit">
            <span class="at">@</span>
            <input
              value={link.value}
              onInput={(e) => (link.value = (e.target as HTMLInputElement).value)}
              placeholder={`Optional — leave empty for a private ${kind.value}`}
              maxlength={32}
              spellcheck={false}
              autocapitalize="none"
            />
          </span>
          {kind.value === 'group' && !!link.value.trim() &&
            <span class="hint">A public group becomes a supergroup.</span>}
        </label>

        <p class="label">
          Members ({selected.value.size})
          {kind.value === 'channel' && <span class="muted">— optional</span>}
        </p>
        <input
          class="search"
          placeholder="Search contacts"
          value={query.value}
          onInput={(e) => (query.value = (e.target as HTMLInputElement).value)}
        />

        <div class="list">
          {filtered.map((dialog) => (
            <button
              key={dialog.peerId}
              class={['row', selected.value.has(dialog.peerId) && 'on'].filter(Boolean).join(' ')}
              onClick={() => toggle(dialog.peerId)}
            >
              <span class="check">{selected.value.has(dialog.peerId) ? '☑' : '☐'}</span>
              <Avatar peerId={dialog.peerId} title={dialog.title} size={32} />
              <span class="name">{dialog.title}</span>
            </button>
          ))}
          {!filtered.length && <p class="muted">No contacts found.</p>}
        </div>

        {error.value && <p class="error">{error.value}</p>}
        {createdPeerId.value !== null && !!error.value &&
          <p class="hint">The {kind.value} was created — only the link failed.</p>}

        <footer>
          <span class="spacer"></span>
          {createdPeerId.value !== null ?
            <button onClick={() => oncreated(createdPeerId.value!)} disabled={busy.value}>Open without link</button> :
            <button onClick={onclose} disabled={busy.value}>Cancel</button>}
          <button
            class="primary"
            onClick={create}
            disabled={busy.value || !canCreate.value}
          >
            {busy.value ? 'Creating…' : createdPeerId.value !== null ? 'Retry link' : 'Create'}
          </button>
        </footer>
      </div>
    </div>
  );
}
