// svelte/src/lib/components/StickerSetSheet.svelte
<script lang="ts">
  import Sticker from './Sticker.svelte';
  import {
    loadSetPreview,
    stickerSetOfDoc,
    toggleSetInstalled,
    type StickerSetPreview
  } from '$lib/telegram/stickers';

  let {
    setKey = '',
    docId = '',
    onsend,
    onclose
  }: {
    /** Set id, short name or the short name out of a t.me/addstickers link. */
    setKey?: string;
    /** A sticker's document id — opens the pack that sticker belongs to. */
    docId?: string;
    onsend?: (docId: string) => void;
    onclose: () => void;
  } = $props();

  let preview = $state<StickerSetPreview | null>(null);
  let loading = $state(true);
  let busy = $state(false);
  let error = $state('');

  $effect(() => {
    const key = setKey;
    const doc = docId;
    let cancelled = false;

    loading = true;
    error = '';
    (doc ? stickerSetOfDoc(doc) : loadSetPreview(key))
      .then((result) => {
        if (cancelled) return;
        preview = result;
        if (!result) error = 'Sticker set not found';
      })
      .catch((err: any) => {
        if (!cancelled) error = err?.type || err?.message || 'Failed to open the set';
      })
      .finally(() => {
        if (!cancelled) loading = false;
      });

    return () => {
      cancelled = true;
    };
  });

  async function toggle() {
    if (!preview || busy) return;
    busy = true;
    try {
      const installed = await toggleSetInstalled(preview.info.id);
      preview = {...preview, info: {...preview.info, installed, archived: false}};
    } catch (err: any) {
      error = err?.type || err?.message || 'Failed to update the set';
    } finally {
      busy = false;
    }
  }
</script>

<div class="backdrop" onclick={onclose} role="presentation"></div>
<div class="sheet">
  <header>
    <strong>{preview?.info.title || 'Sticker set'}</strong>
    <button class="close" onclick={onclose} aria-label="Close">✕</button>
  </header>

  <div class="body">
    {#if loading}
      <p class="muted">Loading…</p>
    {:else if error}
      <p class="muted">{error}</p>
    {:else if preview}
      <div class="grid">
        {#each preview.stickers as sticker (sticker.docId)}
          <button
            class="tile"
            onclick={() => {
              onsend?.(sticker.docId);
              onclose();
            }}
          >
            <Sticker {sticker} size={72} />
          </button>
        {/each}
      </div>
    {/if}
  </div>

  {#if preview}
    <footer>
      <button class="primary" onclick={toggle} disabled={busy}>
        {preview.info.installed ? 'Remove stickers' : `Add ${preview.info.count || ''} stickers`.trim()}
      </button>
    </footer>
  {/if}
</div>

<style>
  .backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.4);
    z-index: 40;
  }

  .sheet {
    position: fixed;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    width: min(420px, calc(100vw - 32px));
    max-height: min(70vh, 560px);
    display: flex;
    flex-direction: column;
    background: var(--bg-elevated);
    border: 1px solid var(--border);
    border-radius: 12px;
    box-shadow: 0 18px 48px rgba(0, 0, 0, 0.35);
    z-index: 41;
    overflow: hidden;
  }

  header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    padding: 12px 14px;
    border-bottom: 1px solid var(--border);
  }

  .close {
    background: none;
    border: none;
    color: var(--text-dim);
    cursor: pointer;
    font-size: 14px;
  }

  .body {
    flex: 1;
    min-height: 0;
    overflow-y: auto;
    padding: 10px 12px;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(76px, 1fr));
    gap: 4px;
  }

  .tile {
    background: none;
    border: none;
    padding: 2px;
    border-radius: 8px;
    cursor: pointer;
  }

  .tile:hover {
    background: color-mix(in srgb, var(--text) 8%, transparent);
  }

  footer {
    padding: 10px 12px;
    border-top: 1px solid var(--border);
  }

  .primary {
    width: 100%;
    padding: 9px;
    border: none;
    border-radius: 8px;
    background: var(--accent);
    color: #fff;
    font-size: 14px;
    cursor: pointer;
  }

  .primary:disabled {
    opacity: 0.6;
    cursor: default;
  }

  .muted {
    color: var(--text-dim);
    padding: 12px;
    font-size: 13px;
  }
</style>

// astro/src/components/StickerSetSheet.tsx
/*
 * Ported from svelte/src/lib/components/StickerSetSheet.svelte.
 *
 * The loader depends on the `setKey` and `docId` *props*, so it is a
 * `useEffect` with both in its dependency list: `useSignalEffect` tracks signal
 * reads only and would never reopen the sheet for another set. The `cancelled`
 * flag is what stops a slow response for the previous set from overwriting the
 * current one.
 *
 * `preview` holds a whole `StickerSetPreview`; its nested fields are never
 * written in place — `toggle` rebuilds the value — because a signal notifies
 * only when the signal itself is assigned.
 */
import {useEffect} from 'preact/hooks';
import {useSignal} from '@preact/signals';

import {
  loadSetPreview,
  stickerSetOfDoc,
  toggleSetInstalled,
  type StickerSetPreview
} from '$lib/telegram/stickers';

import {Sticker} from './Sticker';

import './StickerSetSheet.css';

interface Props {
  /** Set id, short name or the short name out of a t.me/addstickers link. */
  setKey?: string;
  /** A sticker's document id — opens the pack that sticker belongs to. */
  docId?: string;
  onsend?: (docId: string) => void;
  onclose: () => void;
}

export function StickerSetSheet({setKey = '', docId = '', onsend, onclose}: Props) {
  const preview = useSignal<StickerSetPreview | null>(null);
  const loading = useSignal(true);
  const busy = useSignal(false);
  const error = useSignal('');

  useEffect(() => {
    const key = setKey;
    const doc = docId;
    let cancelled = false;

    loading.value = true;
    error.value = '';
    (doc ? stickerSetOfDoc(doc) : loadSetPreview(key))
      .then((result) => {
        if(cancelled) return;
        preview.value = result;
        if(!result) error.value = 'Sticker set not found';
      })
      .catch((err: any) => {
        if(!cancelled) error.value = err?.type || err?.message || 'Failed to open the set';
      })
      .finally(() => {
        if(!cancelled) loading.value = false;
      });

    return () => {
      cancelled = true;
    };
  }, [setKey, docId]);

  async function toggle() {
    if(!preview.value || busy.value) return;
    busy.value = true;
    try {
      const installed = await toggleSetInstalled(preview.value.info.id);
      preview.value = {...preview.value, info: {...preview.value.info, installed, archived: false}};
    } catch(err: any) {
      error.value = err?.type || err?.message || 'Failed to update the set';
    } finally {
      busy.value = false;
    }
  }

  return (
    <>
      <div class="backdrop" onClick={onclose} role="presentation"></div>
      <div class="sheet">
        <header>
          <strong>{preview.value?.info.title || 'Sticker set'}</strong>
          <button class="close" onClick={onclose} aria-label="Close">✕</button>
        </header>

        <div class="body">
          {loading.value ?
            <p class="muted">Loading…</p> :
            error.value ?
              <p class="muted">{error.value}</p> :
              preview.value ?
                <div class="grid">
                  {preview.value.stickers.map((sticker) => (
                    <button
                      key={sticker.docId}
                      class="tile"
                      onClick={() => {
                        onsend?.(sticker.docId);
                        onclose();
                      }}
                    >
                      <Sticker sticker={sticker} size={72} />
                    </button>
                  ))}
                </div> :
                null}
        </div>

        {preview.value && (
          <footer>
            <button class="primary" onClick={toggle} disabled={busy.value}>
              {preview.value.info.installed ? 'Remove stickers' : `Add ${preview.value.info.count || ''} stickers`.trim()}
            </button>
          </footer>
        )}
      </div>
    </>
  );
}
