// astro/src/components/AppearanceSettings.tsx
/*
 * Settings → Appearance: theme (including an auto-night schedule), accent,
 * wallpaper, peer name colour, text size, bubble spacing, power saving and
 * the language pack. Everything it changes is applied through
 * $lib/telegram/appearance, which writes CSS variables on <html>.
 *
 * Ported from svelte/src/lib/components/AppearanceSettings.svelte. The `$effect`
 * that loads a tab's data the first time the tab is opened is a
 * `useSignalEffect` here — it reads the `panel` signal, and that is the hook
 * which tracks signal reads. The `$derived` values become `useComputed` for the
 * same reason, and every read/write of a rune gains a `.value`.
 */
import {Fragment} from 'preact';
import {useComputed, useSignal, useSignalEffect} from '@preact/signals';

import {
  ACCENTS,
  getAccent,
  getDensity,
  getNightSchedule,
  getThemeMode,
  minutesToTime,
  setAccent,
  setDensity,
  setNightSchedule,
  setThemeMode,
  timeToMinutes,
  type Density,
  type NightSchedule,
  type ThemeMode
} from '$lib/telegram/theme';
import {
  COLOR_PRESETS,
  DEFAULT_WALLPAPER,
  LITE_MODE_KEYS,
  MAX_TEXT_SIZE,
  MIN_TEXT_SIZE,
  currentLanguage,
  getBubbleSpacing,
  getTextSize,
  getWallpaper,
  loadBackgroundEmojis,
  loadLanguages,
  loadLiteMode,
  loadOwnColor,
  loadPeerColors,
  loadWallpapers,
  peerNameColor,
  saveOwnColor,
  setBubbleSpacing,
  setLanguage,
  setLiteModeFlag,
  setTextSize,
  setWallpaper,
  uploadWallpaper,
  wallpaperChoiceOf,
  wallpaperPreviewCss,
  type BackgroundEmoji,
  type BubbleSpacing,
  type LanguageItem,
  type LiteModeFlags,
  type OwnColorState,
  type PeerColorOption,
  type WallpaperChoice,
  type WallpaperItem
} from '$lib/telegram/appearance';

import './AppearanceSettings.css';

type Panel = 'theme' | 'wallpaper' | 'colors' | 'motion' | 'language';

// The literal lists the markup iterated over inline. They are typed here so the
// `as Panel` / `as ThemeMode` casts the original carried at each `onclick` drop
// away — the values are already the right union.
const PANEL_TABS: [Panel, string][] = [
  ['theme', 'Theme'],
  ['wallpaper', 'Wallpaper'],
  ['colors', 'Colours'],
  ['motion', 'Animations'],
  ['language', 'Language']
];
const THEME_MODES: ThemeMode[] = ['system', 'light', 'dark', 'schedule'];
const SPACINGS: BubbleSpacing[] = ['roomy', 'compact'];
const DENSITIES: Density[] = ['comfortable', 'console'];

export function AppearanceSettings() {
  const panel = useSignal<Panel>('theme');

  const theme = useSignal<ThemeMode>(getThemeMode());
  const schedule = useSignal<NightSchedule>(getNightSchedule());
  const accent = useSignal(getAccent());
  const density = useSignal<Density>(getDensity());
  const textSize = useSignal(getTextSize());
  const spacing = useSignal<BubbleSpacing>(getBubbleSpacing());

  const wallpapers = useSignal<WallpaperItem[]>([]);
  const wallpaper = useSignal<WallpaperChoice>(getWallpaper());
  const wallpaperBusy = useSignal(false);

  const palette = useSignal<PeerColorOption[]>([]);
  const ownColor = useSignal<OwnColorState | null>(null);
  const backgroundEmojis = useSignal<BackgroundEmoji[]>([]);

  const lite = useSignal<LiteModeFlags>({});
  const languages = useSignal<LanguageItem[]>([]);
  const langCode = useSignal('');
  const languageFilter = useSignal('');

  const error = useSignal('');
  const status = useSignal('');

  function flash(message: string) {
    status.value = message;
    setTimeout(() => (status.value = ''), 2500);
  }

  function fail(err: any, fallback: string) {
    error.value = err?.type || err?.message || fallback;
  }

  // Each tab loads its data on first open and caches it in its own signal. The
  // effect reads `panel`, so it re-runs on every tab switch; the emptiness
  // guards are what keep the caches from reloading.
  useSignalEffect(() => {
    const current = panel.value;
    error.value = '';

    (async() => {
      try {
        if(current === 'wallpaper' && !wallpapers.value.length) {
          wallpapers.value = await loadWallpapers();
        } else if(current === 'colors' && !palette.value.length) {
          const [nextPalette, nextOwnColor] = await Promise.all([loadPeerColors(), loadOwnColor()]);
          palette.value = nextPalette;
          ownColor.value = nextOwnColor;
          backgroundEmojis.value = await loadBackgroundEmojis().catch(() => []);
        } else if(current === 'motion' && !Object.keys(lite.value).length) {
          lite.value = await loadLiteMode();
        } else if(current === 'language' && !languages.value.length) {
          const [nextLanguages, nextCode] = await Promise.all([loadLanguages(), currentLanguage()]);
          languages.value = nextLanguages;
          langCode.value = nextCode;
        }
      } catch(err: any) {
        fail(err, 'Failed to load');
      }
    })();
  });

  const wallpaperColors = useComputed(() => wallpaper.value.colors ?? []);

  const filteredLanguages = useComputed(() =>
    languageFilter.value.trim()
      ? languages.value.filter((language) => {
          const needle = languageFilter.value.trim().toLowerCase();
          return (
            language.name.toLowerCase().includes(needle) ||
            language.nativeName.toLowerCase().includes(needle) ||
            language.code.toLowerCase().includes(needle)
          );
        })
      : languages.value
  );

  const animationsOn = useComputed(() => !(lite.value.all || lite.value.animations));

  async function pickWallpaper(choice: WallpaperChoice) {
    wallpaperBusy.value = true;
    try {
      wallpaper.value = choice;
      await setWallpaper(choice);
    } catch(err: any) {
      fail(err, 'Failed to apply the wallpaper');
    } finally {
      wallpaperBusy.value = false;
    }
  }

  async function toggleBlur() {
    await pickWallpaper({...wallpaper.value, blur: !wallpaper.value.blur});
  }

  async function changeIntensity(value: number) {
    await pickWallpaper({...wallpaper.value, intensity: value});
  }

  async function onUpload(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    input.value = '';
    if(!file) return;

    wallpaperBusy.value = true;
    try {
      wallpaper.value = await uploadWallpaper(file, !!wallpaper.value.blur);
      flash('Wallpaper set');
    } catch(err: any) {
      fail(err, 'Failed to read the image');
    } finally {
      wallpaperBusy.value = false;
    }
  }

  async function pickOwnColor(colorId: number | null) {
    if(!ownColor.value) return;
    const previous = ownColor.value;
    ownColor.value = {...ownColor.value, colorId};
    try {
      await saveOwnColor(colorId, ownColor.value.backgroundEmojiId);
      flash('Name colour saved');
    } catch(err: any) {
      ownColor.value = previous;
      fail(err, 'Failed to save the colour');
    }
  }

  async function pickBackgroundEmoji(docId: string | null) {
    if(!ownColor.value) return;
    const previous = ownColor.value;
    ownColor.value = {...ownColor.value, backgroundEmojiId: docId};
    try {
      await saveOwnColor(ownColor.value.colorId, docId);
      flash(docId ? 'Pattern saved' : 'Pattern removed');
    } catch(err: any) {
      ownColor.value = previous;
      fail(err, 'Failed to save the pattern');
    }
  }

  async function toggleLite(key: string, disabled: boolean) {
    lite.value = {...lite.value, [key]: disabled};
    try {
      await setLiteModeFlag(key, disabled);
    } catch(err: any) {
      lite.value = {...lite.value, [key]: !disabled};
      fail(err, 'Failed to save');
    }
  }

  async function pickLanguage(code: string) {
    const previous = langCode.value;
    langCode.value = code;
    try {
      await setLanguage(code);
      flash('Language pack applied');
    } catch(err: any) {
      langCode.value = previous;
      fail(err, 'Failed to switch the language');
    }
  }

  // The `{#if} {:else if} … {:else}` chain that picked the open tab's body,
  // resolved before the single return.
  let body: preact.JSX.Element;

  if(panel.value === 'theme') {
    body = (
      <>
        <p class="label">Theme</p>
        <div class="chips">
          {THEME_MODES.map((mode, i) => (
            <button
              key={i}
              class={theme.value === mode ? 'on' : ''}
              onClick={() => {
                theme.value = mode;
                setThemeMode(theme.value);
              }}>{mode === 'schedule' ? 'auto night' : mode}</button>
          ))}
        </div>

        {theme.value === 'schedule' && (
          <>
            <div class="row">
              <label class="field">
                <span>Dark from</span>
                <input
                  type="time"
                  value={minutesToTime(schedule.value.from)}
                  onChange={(e) => {
                    schedule.value = {...schedule.value, from: timeToMinutes((e.target as HTMLInputElement).value)};
                    setNightSchedule(schedule.value);
                  }}
                />
              </label>
              <label class="field">
                <span>Back to light</span>
                <input
                  type="time"
                  value={minutesToTime(schedule.value.to)}
                  onChange={(e) => {
                    schedule.value = {...schedule.value, to: timeToMinutes((e.target as HTMLInputElement).value)};
                    setNightSchedule(schedule.value);
                  }}
                />
              </label>
            </div>
            <p class="muted small">
              Checked every half minute against the device clock — a range that crosses midnight is fine.
            </p>
          </>
        )}

        <p class="label">Accent</p>
        <div class="swatches">
          {ACCENTS.map((option, i) => (
            <button
              key={i}
              class={['swatch', accent.value === option.value && 'on'].filter(Boolean).join(' ')}
              style={{background: option.value}}
              title={option.name}
              aria-label={option.name}
              onClick={() => {
                accent.value = option.value;
                setAccent(accent.value);
              }}
            ></button>
          ))}
        </div>

        <p class="label">Message text size — {textSize.value}px</p>
        <input
          class="slider"
          type="range"
          min={MIN_TEXT_SIZE}
          max={MAX_TEXT_SIZE}
          value={textSize.value}
          onInput={(e) => {
            textSize.value = +(e.target as HTMLInputElement).value;
            setTextSize(textSize.value);
          }}
        />

        <p class="label">Bubble spacing</p>
        <div class="chips">
          {SPACINGS.map((option, i) => (
            <button
              key={i}
              class={spacing.value === option ? 'on' : ''}
              onClick={() => {
                spacing.value = option;
                setBubbleSpacing(spacing.value);
              }}>{option}</button>
          ))}
        </div>

        <p class="label">Density</p>
        <div class="chips">
          {DENSITIES.map((option, i) => (
            <button
              key={i}
              class={density.value === option ? 'on' : ''}
              onClick={() => {
                density.value = option;
                setDensity(density.value);
              }}>{option}</button>
          ))}
        </div>
        <p class="muted small">
          Console swaps bubbles for an aligned monospace grid and keeps its own spacing — the text size
          still applies, the bubble spacing does not.
        </p>
      </>
    );
  } else if(panel.value === 'wallpaper') {
    body = (
      <>
        <div class="chips">
          <button class={wallpaper.value.kind === 'default' ? 'on' : ''} onClick={() => pickWallpaper(DEFAULT_WALLPAPER)}
            >none</button>
          <button class={!!wallpaper.value.blur ? 'on' : ''} onClick={toggleBlur} disabled={wallpaper.value.kind === 'default'}
            >blur</button>
          <label class="upload">
            upload
            <input type="file" accept="image/*" onChange={onUpload} />
          </label>
        </div>
        {wallpaperBusy.value && <p class="muted small">Applying…</p>}

        {wallpaper.value.pattern && (
          <>
            <p class="label">Pattern intensity — {wallpaper.value.intensity ?? 40}%</p>
            <input
              class="slider"
              type="range"
              min="5"
              max="100"
              value={wallpaper.value.intensity ?? 40}
              onChange={(e) => changeIntensity(+(e.target as HTMLInputElement).value)}
            />
          </>
        )}

        <p class="label">Colours and gradients</p>
        <div class="grid">
          {COLOR_PRESETS.map((preset, i) => (
            <button
              key={i}
              class={['tile', wallpaper.value.kind === 'color' && wallpaper.value.colors?.join() === preset.colors.join() && 'on'].filter(Boolean).join(' ')}
              style={{
                background: wallpaperPreviewCss({
                  id: preset.name,
                  slug: '',
                  colors: preset.colors,
                  rotation: preset.rotation,
                  intensity: 0,
                  pattern: false,
                  dark: false,
                  hasFile: false
                })
              }}
              title={preset.name}
              aria-label={preset.name}
              onClick={() =>
                pickWallpaper({
                  kind: 'color',
                  colors: preset.colors,
                  rotation: preset.rotation
                })}
            ></button>
          ))}
        </div>

        <p class="label">From Telegram</p>
        {!wallpapers.value.length ?
          <p class="muted small">Loading…</p> :
          <div class="grid">
            {wallpapers.value.map((item) => (
              <button
                key={item.id}
                class={['tile', wallpaper.value.slug === item.slug && wallpaper.value.kind === 'wallpaper' && 'on'].filter(Boolean).join(' ')}
                style={{background: wallpaperPreviewCss(item)}}
                title={item.slug}
                aria-label={item.slug || 'Wallpaper'}
                onClick={() => pickWallpaper(wallpaperChoiceOf(item, !!wallpaper.value.blur))}
              ></button>
            ))}
          </div>}

        {wallpaperColors.value.length > 0 && (
          <p class="muted small">
            Gradient: {wallpaperColors.value.join(' · ')}
          </p>
        )}
        <p class="muted small">
          The wallpaper applies to every chat. Per-chat wallpapers need{' '}
          <code>messages.setChatWallPaper</code>, which the shared manager layer does not wrap yet.
          Uploaded images stay on this device — they are not saved to your Telegram account.
        </p>
      </>
    );
  } else if(panel.value === 'colors') {
    body = (
      <>
        <p class="label">Peer name palette</p>
        {!palette.value.length ?
          <p class="muted small">Loading…</p> :
          <>
            <div class="palette">
              {palette.value.map((option) => (
                <span key={option.id} class="peer-name" style={{color: peerNameColor(option.id, option.id)}}>Aa</span>
              ))}
            </div>
            <p class="muted small">
              Every peer without a colour of its own falls on one of these by id. The palette is published
              as <code>--peer-N-color</code> on the document, and reply strips and names read it from
              there.
            </p>
          </>}

        <p class="label">Your name colour</p>
        {!ownColor.value ?
          <p class="muted small">Loading…</p> :
          !ownColor.value.isPremium ?
            <p class="muted small">
              Choosing your own name colour is a Premium feature — the server rejects the change without
              it.
            </p> :
            <>
              <div class="palette">
                <button
                  class={['peer-pick', ownColor.value.colorId === null && 'on'].filter(Boolean).join(' ')}
                  onClick={() => pickOwnColor(null)}>auto</button>
                {palette.value.map((option) => (
                  <button
                    key={option.id}
                    class={['peer-pick', ownColor.value.colorId === option.id && 'on'].filter(Boolean).join(' ')}
                    style={{color: peerNameColor(option.id, option.id)}}
                    onClick={() => pickOwnColor(option.id)}>Aa</button>
                ))}
              </div>

              <p class="label">Pattern behind your name</p>
              <div class="grid emoji">
                <button
                  class={['tile', 'emoji-tile', !ownColor.value.backgroundEmojiId && 'on'].filter(Boolean).join(' ')}
                  onClick={() => pickBackgroundEmoji(null)}>✕</button>
                {backgroundEmojis.value.map((emoji) => (
                  <button
                    key={emoji.docId}
                    class={['tile', 'emoji-tile', ownColor.value.backgroundEmojiId === emoji.docId && 'on'].filter(Boolean).join(' ')}
                    onClick={() => pickBackgroundEmoji(emoji.docId)}
                  >
                    {emoji.url && <img src={emoji.url} alt="" />}
                  </button>
                ))}
              </div>
            </>}
      </>
    );
  } else if(panel.value === 'motion') {
    body = (
      <>
        <label class="toggle">
          <input
            type="checkbox"
            checked={animationsOn.value}
            onChange={() => toggleLite('all', animationsOn.value)}
          />
          <span>Enable animations</span>
        </label>
        <p class="muted small">
          Off is tweb's power-saving switch: every effect below stops, and transitions across the app are
          cut to nothing.
        </p>

        <p class="label">Power saving</p>
        {/* Each flag is a toggle followed by its own description, so the pair is
            one keyed fragment — `{#each}` could emit two siblings per item. */}
        {LITE_MODE_KEYS.map((option) => (
          <Fragment key={option.key}>
            <label class="toggle">
              <input
                type="checkbox"
                checked={!lite.value.all && !lite.value[option.key]}
                disabled={!!lite.value.all}
                onChange={() => toggleLite(option.key, !lite.value[option.key])}
              />
              <span>{option.label}</span>
            </label>
            <p class="muted small indent">{option.description}</p>
          </Fragment>
        ))}
        <p class="muted small">
          These are the shared <code>liteMode</code> flags, so the Solid client and every other tab honour
          them too. Web S itself acts on the animation and blur flags directly.
        </p>
      </>
    );
  } else {
    body = (
      <>
        <label class="field">
          <span>Search</span>
          <input
            value={languageFilter.value}
            onInput={(e) => (languageFilter.value = (e.target as HTMLInputElement).value)}
            placeholder="Language"
          />
        </label>
        {!languages.value.length ?
          <p class="muted small">Loading…</p> :
          filteredLanguages.value.map((language) => (
            <button
              key={language.code}
              class={['language', langCode.value === language.code && 'on'].filter(Boolean).join(' ')}
              onClick={() => pickLanguage(language.code)}>
              <span class="language-name">{language.name}</span>
              <span class="muted small">
                {language.nativeName}{language.total ?
                  ` · ${Math.round((language.translated / language.total) * 100)}% translated` :
                  ''}
              </span>
            </button>
          ))}
        <p class="muted small">
          This switches the shared lang pack: the dates, plurals and strings that come from the tweb
          layer follow it, and an RTL language flips the document direction. Web S's own labels — these
          settings, the composer, the chat header — are hardcoded English and do not translate yet.
        </p>
      </>
    );
  }

  return (
    <div class="appearance">
      {error.value && <p class="error">{error.value}</p>}
      {status.value && <p class="ok">{status.value}</p>}

      <div class="panels">
        {PANEL_TABS.map(([key, label], i) => (
          <button key={i} class={panel.value === key ? 'on' : ''} onClick={() => (panel.value = key)}>{label}</button>
        ))}
      </div>

      {body}
    </div>
  );
}

// svelte/src/lib/components/AppearanceSettings.svelte
<script lang="ts">
  /**
   * Settings → Appearance: theme (including an auto-night schedule), accent,
   * wallpaper, peer name colour, text size, bubble spacing, power saving and
   * the language pack. Everything it changes is applied through
   * $lib/telegram/appearance, which writes CSS variables on <html>.
   */
  import {
    ACCENTS,
    getAccent,
    getDensity,
    getNightSchedule,
    getThemeMode,
    minutesToTime,
    setAccent,
    setDensity,
    setNightSchedule,
    setThemeMode,
    timeToMinutes,
    type Density,
    type NightSchedule,
    type ThemeMode
  } from '$lib/telegram/theme';
  import {
    COLOR_PRESETS,
    DEFAULT_WALLPAPER,
    LITE_MODE_KEYS,
    MAX_TEXT_SIZE,
    MIN_TEXT_SIZE,
    currentLanguage,
    getBubbleSpacing,
    getTextSize,
    getWallpaper,
    loadBackgroundEmojis,
    loadLanguages,
    loadLiteMode,
    loadOwnColor,
    loadPeerColors,
    loadWallpapers,
    peerNameColor,
    saveOwnColor,
    setBubbleSpacing,
    setLanguage,
    setLiteModeFlag,
    setTextSize,
    setWallpaper,
    uploadWallpaper,
    wallpaperChoiceOf,
    wallpaperPreviewCss,
    type BackgroundEmoji,
    type BubbleSpacing,
    type LanguageItem,
    type LiteModeFlags,
    type OwnColorState,
    type PeerColorOption,
    type WallpaperChoice,
    type WallpaperItem
  } from '$lib/telegram/appearance';

  type Panel = 'theme' | 'wallpaper' | 'colors' | 'motion' | 'language';
  let panel = $state<Panel>('theme');

  let theme = $state<ThemeMode>(getThemeMode());
  let schedule = $state<NightSchedule>(getNightSchedule());
  let accent = $state(getAccent());
  let density = $state<Density>(getDensity());
  let textSize = $state(getTextSize());
  let spacing = $state<BubbleSpacing>(getBubbleSpacing());

  let wallpapers = $state<WallpaperItem[]>([]);
  let wallpaper = $state<WallpaperChoice>(getWallpaper());
  let wallpaperBusy = $state(false);

  let palette = $state<PeerColorOption[]>([]);
  let ownColor = $state<OwnColorState | null>(null);
  let backgroundEmojis = $state<BackgroundEmoji[]>([]);

  let lite = $state<LiteModeFlags>({});
  let languages = $state<LanguageItem[]>([]);
  let langCode = $state('');
  let languageFilter = $state('');

  let error = $state('');
  let status = $state('');

  function flash(message: string) {
    status = message;
    setTimeout(() => (status = ''), 2500);
  }

  function fail(err: any, fallback: string) {
    error = err?.type || err?.message || fallback;
  }

  $effect(() => {
    const current = panel;
    error = '';

    (async () => {
      try {
        if (current === 'wallpaper' && !wallpapers.length) {
          wallpapers = await loadWallpapers();
        } else if (current === 'colors' && !palette.length) {
          [palette, ownColor] = await Promise.all([loadPeerColors(), loadOwnColor()]);
          backgroundEmojis = await loadBackgroundEmojis().catch(() => []);
        } else if (current === 'motion' && !Object.keys(lite).length) {
          lite = await loadLiteMode();
        } else if (current === 'language' && !languages.length) {
          [languages, langCode] = await Promise.all([loadLanguages(), currentLanguage()]);
        }
      } catch (err: any) {
        fail(err, 'Failed to load');
      }
    })();
  });

  const wallpaperColors = $derived(wallpaper.colors ?? []);

  const filteredLanguages = $derived(
    languageFilter.trim()
      ? languages.filter((language) => {
          const needle = languageFilter.trim().toLowerCase();
          return (
            language.name.toLowerCase().includes(needle) ||
            language.nativeName.toLowerCase().includes(needle) ||
            language.code.toLowerCase().includes(needle)
          );
        })
      : languages
  );

  const animationsOn = $derived(!(lite.all || lite.animations));

  async function pickWallpaper(choice: WallpaperChoice) {
    wallpaperBusy = true;
    try {
      wallpaper = choice;
      await setWallpaper(choice);
    } catch (err: any) {
      fail(err, 'Failed to apply the wallpaper');
    } finally {
      wallpaperBusy = false;
    }
  }

  async function toggleBlur() {
    await pickWallpaper({...wallpaper, blur: !wallpaper.blur});
  }

  async function changeIntensity(value: number) {
    await pickWallpaper({...wallpaper, intensity: value});
  }

  async function onUpload(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    input.value = '';
    if (!file) return;

    wallpaperBusy = true;
    try {
      wallpaper = await uploadWallpaper(file, !!wallpaper.blur);
      flash('Wallpaper set');
    } catch (err: any) {
      fail(err, 'Failed to read the image');
    } finally {
      wallpaperBusy = false;
    }
  }

  async function pickOwnColor(colorId: number | null) {
    if (!ownColor) return;
    const previous = ownColor;
    ownColor = {...ownColor, colorId};
    try {
      await saveOwnColor(colorId, ownColor.backgroundEmojiId);
      flash('Name colour saved');
    } catch (err: any) {
      ownColor = previous;
      fail(err, 'Failed to save the colour');
    }
  }

  async function pickBackgroundEmoji(docId: string | null) {
    if (!ownColor) return;
    const previous = ownColor;
    ownColor = {...ownColor, backgroundEmojiId: docId};
    try {
      await saveOwnColor(ownColor.colorId, docId);
      flash(docId ? 'Pattern saved' : 'Pattern removed');
    } catch (err: any) {
      ownColor = previous;
      fail(err, 'Failed to save the pattern');
    }
  }

  async function toggleLite(key: string, disabled: boolean) {
    lite = {...lite, [key]: disabled};
    try {
      await setLiteModeFlag(key, disabled);
    } catch (err: any) {
      lite = {...lite, [key]: !disabled};
      fail(err, 'Failed to save');
    }
  }

  async function pickLanguage(code: string) {
    const previous = langCode;
    langCode = code;
    try {
      await setLanguage(code);
      flash('Language pack applied');
    } catch (err: any) {
      langCode = previous;
      fail(err, 'Failed to switch the language');
    }
  }
</script>

<div class="appearance">
  {#if error}<p class="error">{error}</p>{/if}
  {#if status}<p class="ok">{status}</p>{/if}

  <div class="panels">
    {#each [['theme', 'Theme'], ['wallpaper', 'Wallpaper'], ['colors', 'Colours'], ['motion', 'Animations'], ['language', 'Language']] as [key, label]}
      <button class:on={panel === key} onclick={() => (panel = key as Panel)}>{label}</button>
    {/each}
  </div>

  {#if panel === 'theme'}
    <p class="label">Theme</p>
    <div class="chips">
      {#each ['system', 'light', 'dark', 'schedule'] as mode}
        <button
          class:on={theme === mode}
          onclick={() => {
            theme = mode as ThemeMode;
            setThemeMode(theme);
          }}>{mode === 'schedule' ? 'auto night' : mode}</button
        >
      {/each}
    </div>

    {#if theme === 'schedule'}
      <div class="row">
        <label class="field"
          ><span>Dark from</span>
          <input
            type="time"
            value={minutesToTime(schedule.from)}
            onchange={(e) => {
              schedule = {...schedule, from: timeToMinutes(e.currentTarget.value)};
              setNightSchedule(schedule);
            }}
          /></label
        >
        <label class="field"
          ><span>Back to light</span>
          <input
            type="time"
            value={minutesToTime(schedule.to)}
            onchange={(e) => {
              schedule = {...schedule, to: timeToMinutes(e.currentTarget.value)};
              setNightSchedule(schedule);
            }}
          /></label
        >
      </div>
      <p class="muted small">
        Checked every half minute against the device clock — a range that crosses midnight is fine.
      </p>
    {/if}

    <p class="label">Accent</p>
    <div class="swatches">
      {#each ACCENTS as option}
        <button
          class="swatch"
          class:on={accent === option.value}
          style="background: {option.value}"
          title={option.name}
          aria-label={option.name}
          onclick={() => {
            accent = option.value;
            setAccent(accent);
          }}
        ></button>
      {/each}
    </div>

    <p class="label">Message text size — {textSize}px</p>
    <input
      class="slider"
      type="range"
      min={MIN_TEXT_SIZE}
      max={MAX_TEXT_SIZE}
      value={textSize}
      oninput={(e) => {
        textSize = +e.currentTarget.value;
        setTextSize(textSize);
      }}
    />

    <p class="label">Bubble spacing</p>
    <div class="chips">
      {#each ['roomy', 'compact'] as option}
        <button
          class:on={spacing === option}
          onclick={() => {
            spacing = option as BubbleSpacing;
            setBubbleSpacing(spacing);
          }}>{option}</button
        >
      {/each}
    </div>

    <p class="label">Density</p>
    <div class="chips">
      {#each ['comfortable', 'console'] as option}
        <button
          class:on={density === option}
          onclick={() => {
            density = option as Density;
            setDensity(density);
          }}>{option}</button
        >
      {/each}
    </div>
    <p class="muted small">
      Console swaps bubbles for an aligned monospace grid and keeps its own spacing — the text size
      still applies, the bubble spacing does not.
    </p>
  {:else if panel === 'wallpaper'}
    <div class="chips">
      <button class:on={wallpaper.kind === 'default'} onclick={() => pickWallpaper(DEFAULT_WALLPAPER)}
        >none</button
      >
      <button class:on={!!wallpaper.blur} onclick={toggleBlur} disabled={wallpaper.kind === 'default'}
        >blur</button
      >
      <label class="upload">
        upload
        <input type="file" accept="image/*" onchange={onUpload} />
      </label>
    </div>
    {#if wallpaperBusy}<p class="muted small">Applying…</p>{/if}

    {#if wallpaper.pattern}
      <p class="label">Pattern intensity — {wallpaper.intensity ?? 40}%</p>
      <input
        class="slider"
        type="range"
        min="5"
        max="100"
        value={wallpaper.intensity ?? 40}
        onchange={(e) => changeIntensity(+e.currentTarget.value)}
      />
    {/if}

    <p class="label">Colours and gradients</p>
    <div class="grid">
      {#each COLOR_PRESETS as preset}
        <button
          class="tile"
          class:on={wallpaper.kind === 'color' && wallpaper.colors?.join() === preset.colors.join()}
          style="background: {wallpaperPreviewCss({
            id: preset.name,
            slug: '',
            colors: preset.colors,
            rotation: preset.rotation,
            intensity: 0,
            pattern: false,
            dark: false,
            hasFile: false
          })}"
          title={preset.name}
          aria-label={preset.name}
          onclick={() =>
            pickWallpaper({
              kind: 'color',
              colors: preset.colors,
              rotation: preset.rotation
            })}
        ></button>
      {/each}
    </div>

    <p class="label">From Telegram</p>
    {#if !wallpapers.length}
      <p class="muted small">Loading…</p>
    {:else}
      <div class="grid">
        {#each wallpapers as item (item.id)}
          <button
            class="tile"
            class:on={wallpaper.slug === item.slug && wallpaper.kind === 'wallpaper'}
            style="background: {wallpaperPreviewCss(item)}"
            title={item.slug}
            aria-label={item.slug || 'Wallpaper'}
            onclick={() => pickWallpaper(wallpaperChoiceOf(item, !!wallpaper.blur))}
          ></button>
        {/each}
      </div>
    {/if}

    {#if wallpaperColors.length}
      <p class="muted small">
        Gradient: {wallpaperColors.join(' · ')}
      </p>
    {/if}
    <p class="muted small">
      The wallpaper applies to every chat. Per-chat wallpapers need
      <code>messages.setChatWallPaper</code>, which the shared manager layer does not wrap yet.
      Uploaded images stay on this device — they are not saved to your Telegram account.
    </p>
  {:else if panel === 'colors'}
    <p class="label">Peer name palette</p>
    {#if !palette.length}
      <p class="muted small">Loading…</p>
    {:else}
      <div class="palette">
        {#each palette as option (option.id)}
          <span class="peer-name" style="color: {peerNameColor(option.id, option.id)}">Aa</span>
        {/each}
      </div>
      <p class="muted small">
        Every peer without a colour of its own falls on one of these by id. The palette is published
        as <code>--peer-N-color</code> on the document, and reply strips and names read it from
        there.
      </p>
    {/if}

    <p class="label">Your name colour</p>
    {#if !ownColor}
      <p class="muted small">Loading…</p>
    {:else if !ownColor.isPremium}
      <p class="muted small">
        Choosing your own name colour is a Premium feature — the server rejects the change without
        it.
      </p>
    {:else}
      <div class="palette">
        <button
          class="peer-pick"
          class:on={ownColor.colorId === null}
          onclick={() => pickOwnColor(null)}>auto</button
        >
        {#each palette as option (option.id)}
          <button
            class="peer-pick"
            class:on={ownColor.colorId === option.id}
            style="color: {peerNameColor(option.id, option.id)}"
            onclick={() => pickOwnColor(option.id)}>Aa</button
          >
        {/each}
      </div>

      <p class="label">Pattern behind your name</p>
      <div class="grid emoji">
        <button
          class="tile emoji-tile"
          class:on={!ownColor.backgroundEmojiId}
          onclick={() => pickBackgroundEmoji(null)}>✕</button
        >
        {#each backgroundEmojis as emoji (emoji.docId)}
          <button
            class="tile emoji-tile"
            class:on={ownColor.backgroundEmojiId === emoji.docId}
            onclick={() => pickBackgroundEmoji(emoji.docId)}
          >
            {#if emoji.url}<img src={emoji.url} alt="" />{/if}
          </button>
        {/each}
      </div>
    {/if}
  {:else if panel === 'motion'}
    <label class="toggle">
      <input
        type="checkbox"
        checked={animationsOn}
        onchange={() => toggleLite('all', animationsOn)}
      />
      <span>Enable animations</span>
    </label>
    <p class="muted small">
      Off is tweb's power-saving switch: every effect below stops, and transitions across the app are
      cut to nothing.
    </p>

    <p class="label">Power saving</p>
    {#each LITE_MODE_KEYS as option (option.key)}
      <label class="toggle">
        <input
          type="checkbox"
          checked={!lite.all && !lite[option.key]}
          disabled={!!lite.all}
          onchange={() => toggleLite(option.key, !lite[option.key])}
        />
        <span>{option.label}</span>
      </label>
      <p class="muted small indent">{option.description}</p>
    {/each}
    <p class="muted small">
      These are the shared <code>liteMode</code> flags, so the Solid client and every other tab honour
      them too. Web S itself acts on the animation and blur flags directly.
    </p>
  {:else}
    <label class="field"
      ><span>Search</span><input bind:value={languageFilter} placeholder="Language" /></label
    >
    {#if !languages.length}
      <p class="muted small">Loading…</p>
    {:else}
      {#each filteredLanguages as language (language.code)}
        <button class="language" class:on={langCode === language.code} onclick={() => pickLanguage(language.code)}>
          <span class="language-name">{language.name}</span>
          <span class="muted small">
            {language.nativeName}{language.total
              ? ` · ${Math.round((language.translated / language.total) * 100)}% translated`
              : ''}
          </span>
        </button>
      {/each}
    {/if}
    <p class="muted small">
      This switches the shared lang pack: the dates, plurals and strings that come from the tweb
      layer follow it, and an RTL language flips the document direction. Web S's own labels — these
      settings, the composer, the chat header — are hardcoded English and do not translate yet.
    </p>
  {/if}
</div>

<style>
  .appearance {
    display: grid;
    gap: 10px;
    align-content: start;
  }

  .panels {
    display: flex;
    gap: 4px;
    overflow-x: auto;
    padding-bottom: 2px;
  }

  .panels button {
    flex: none;
    padding: 5px 10px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: transparent;
    color: var(--text-dim);
    cursor: pointer;
    font-size: 12px;
  }

  .panels button.on {
    background: var(--accent);
    border-color: transparent;
    color: #fff;
  }

  .label {
    margin: 8px 0 0;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--text-dim);
  }

  .chips {
    display: flex;
    gap: 6px;
    flex-wrap: wrap;
    align-items: center;
  }

  .chips button,
  .upload {
    padding: 6px 12px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: transparent;
    color: inherit;
    cursor: pointer;
    font-size: 13px;
    text-transform: capitalize;
  }

  .chips button.on,
  .upload:hover {
    background: var(--accent);
    border-color: transparent;
    color: #fff;
  }

  .chips button:disabled {
    opacity: 0.45;
    cursor: default;
  }

  .upload input {
    display: none;
  }

  .row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
  }

  .field {
    display: grid;
    gap: 4px;
    font-size: 12px;
    color: var(--text-dim);
  }

  .field input {
    padding: 8px 10px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: var(--text);
    outline: none;
  }

  .field input:focus {
    border-color: var(--accent);
  }

  .slider {
    width: 100%;
    accent-color: var(--accent);
  }

  .swatches {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
  }

  .swatch {
    width: 28px;
    height: 28px;
    border-radius: 50%;
    border: 2px solid transparent;
    cursor: pointer;
  }

  .swatch.on {
    border-color: var(--text);
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(64px, 1fr));
    gap: 6px;
  }

  .tile {
    aspect-ratio: 3 / 4;
    border-radius: 8px;
    border: 2px solid transparent;
    cursor: pointer;
    padding: 0;
  }

  .tile.on {
    border-color: var(--text);
  }

  .grid.emoji {
    grid-template-columns: repeat(auto-fill, minmax(40px, 1fr));
  }

  .emoji-tile {
    aspect-ratio: 1;
    background: var(--bg-elevated);
    color: inherit;
    display: grid;
    place-items: center;
  }

  .emoji-tile img {
    width: 26px;
    height: 26px;
    object-fit: contain;
  }

  .palette {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
    align-items: center;
  }

  .peer-name,
  .peer-pick {
    font-weight: 700;
    font-size: 15px;
  }

  .peer-pick {
    padding: 4px 8px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: transparent;
    cursor: pointer;
  }

  .peer-pick.on {
    border-color: var(--text);
  }

  .toggle {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
  }

  .language {
    display: grid;
    gap: 2px;
    padding: 8px 10px;
    border: 1px solid var(--border);
    border-radius: 10px;
    background: transparent;
    color: inherit;
    cursor: pointer;
    text-align: left;
  }

  .language.on {
    border-color: var(--accent);
    background: var(--row-active);
  }

  .language-name {
    font-size: 14px;
    font-weight: 500;
  }

  .muted {
    color: var(--text-dim);
  }

  .small {
    font-size: 12px;
    margin: 0;
  }

  .indent {
    margin-left: 24px;
    margin-top: -4px;
  }

  .error {
    margin: 0;
    color: var(--danger);
    font-size: 13px;
  }

  .ok {
    margin: 0;
    color: var(--accent);
    font-size: 13px;
  }
</style>
