// astro/src/components/InlinePreview.tsx
/*
 * Ported from svelte/src/lib/components/InlinePreview.svelte.
 *
 * Two effect subtleties, both from the conversion contract:
 *  - `bind:this={el}` became `ref`, so the observer effect reads `el.current`
 *    after the commit instead of watching a `$state` node;
 *  - the loader effect reads a *prop* (`result.queryAndResultId`, the property
 *    Svelte tracked) and the signal `seen`, so it is a `useEffect` keyed on both
 *    — `useSignalEffect` tracks signal reads only and would never notice a
 *    different result. `seen` stays a signal because it is what makes that effect
 *    run, exactly as `$state` did.
 */
import {useEffect, useRef} from 'preact/hooks';
import {useSignal} from '@preact/signals';

import {loadInlineResultThumbnail, type InlineResultItem} from '$lib/telegram/settings';
import {enqueueLoad} from '$lib/telegram/loadQueue';

import './InlinePreview.css';

interface Props {
  result: InlineResultItem;
  size?: number;
  isGrid?: boolean;
}

export function InlinePreview({result, size = 44, isGrid = false}: Props) {
  const url = useSignal<string | null>(null);
  const el = useRef<HTMLSpanElement>(null);
  const seen = useSignal(false);

  // Svelte read `result` inside the async callback and always saw the current
  // item; a closure in JSX would see the render that started the load, so the
  // latest id is kept in a ref.
  const currentId = useRef(result.queryAndResultId);
  currentId.current = result.queryAndResultId;

  useEffect(() => {
    const node = el.current;
    if(!node || seen.value) return;

    const observer = new IntersectionObserver((entries) => {
      if(entries.some((entry) => entry.isIntersecting)) {
        seen.value = true;
        observer.disconnect();
      }
    }, {rootMargin: '120px'});

    observer.observe(node);
    return () => observer.disconnect();
  }, [seen.value]);

  useEffect(() => {
    const id = result.queryAndResultId;
    if(!seen.value) return;
    url.value = null;
    enqueueLoad(() => loadInlineResultThumbnail(id)).then((resolved) => {
      if(id === currentId.current) url.value = resolved;
    });
  }, [result.queryAndResultId, seen.value]);

  const fallback = (result.title.trim() || result.type || '?')[0].toUpperCase();

  return (
    <span
      ref={el}
      class={['inline-preview', isGrid && 'grid-mode'].filter(Boolean).join(' ')}
      style={isGrid ? undefined : {width: `${size}px`, height: `${size}px`}}
    >
      {url.value ?
        result.isGif ?
          /* Decorative loop: there are no captions to describe. */
          <video src={url.value} autoplay loop muted playsinline></video> :
          <img src={url.value} alt={result.title} /> :
        <span class="fallback">{fallback}</span>}
    </span>
  );
}

// svelte/src/lib/components/InlinePreview.svelte
<script lang="ts">
  import {loadInlineResultThumbnail, type InlineResultItem} from '$lib/telegram/settings';
  import {enqueueLoad} from '$lib/telegram/loadQueue';

  let {result, size = 44, isGrid = false}: {result: InlineResultItem; size?: number; isGrid?: boolean} = $props();

  let url = $state<string | null>(null);
  let el = $state<HTMLSpanElement | null>(null);
  let seen = $state(false);

  $effect(() => {
    if(!el || seen) return;

    const observer = new IntersectionObserver((entries) => {
      if(entries.some((entry) => entry.isIntersecting)) {
        seen = true;
        observer.disconnect();
      }
    }, {rootMargin: '120px'});

    observer.observe(el);
    return () => observer.disconnect();
  });

  $effect(() => {
    const id = result.queryAndResultId;
    if(!seen) return;
    url = null;
    enqueueLoad(() => loadInlineResultThumbnail(id)).then((resolved) => {
      if(id === result.queryAndResultId) url = resolved;
    });
  });

  const fallback = $derived((result.title.trim() || result.type || '?')[0].toUpperCase());
</script>

<span
  class="inline-preview"
  class:grid-mode={isGrid}
  bind:this={el}
  style={isGrid ? undefined : `width: ${size}px; height: ${size}px`}
>
  {#if url}
    {#if result.isGif}
      <!-- svelte-ignore a11y_media_has_caption -->
      <video src={url} autoplay loop muted playsinline></video>
    {:else}
      <img src={url} alt={result.title} />
    {/if}
  {:else}
    <span class="fallback">{fallback}</span>
  {/if}
</span>

<style>
  .inline-preview {
    display: inline-grid;
    place-items: center;
    border-radius: 8px;
    background: var(--surface-2, color-mix(in srgb, var(--text) 8%, transparent));
    overflow: hidden;
    flex: none;
  }

  .inline-preview.grid-mode {
    width: 100%;
    height: 100%;
    min-height: 80px;
    aspect-ratio: 1;
    border-radius: 6px;
  }

  img,
  video {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .fallback {
    font-size: 16px;
    font-weight: 600;
    color: var(--text-dim);
  }
</style>
