// astro/src/components/SavedTags.tsx
/*
 * Ported from svelte/src/lib/components/SavedTags.svelte.
 *
 * The `$effect` here depends on the `savedPeerId` prop, not on a signal, so it
 * becomes a `useEffect` with that prop in its dependency list —
 * `useSignalEffect` tracks signal reads only and would never re-run.
 */
import {useEffect, useRef} from 'preact/hooks';
import {useSignal} from '@preact/signals';

import {loadSavedTags, renameSavedTag, type SavedTagItem} from '$lib/telegram/topics';

import './SavedTags.css';

interface Props {
  /** Scopes the tag list to one saved sub-chat; undefined means all of Saved. */
  savedPeerId?: number;
  active?: string;
  onselect: (emoticon: string) => void;
}

export function SavedTags({savedPeerId, active = '', onselect}: Props) {
  const tags = useSignal<SavedTagItem[]>([]);
  const renaming = useSignal<string | null>(null);
  const renameValue = useSignal('');
  const error = useSignal('');

  // Svelte compared the scope against the current prop inside the async
  // callback; a closure in JSX would see the value from the render that started
  // the load, so the latest one is kept in a ref.
  const currentSavedPeerId = useRef(savedPeerId);
  currentSavedPeerId.current = savedPeerId;

  async function refresh() {
    tags.value = await loadSavedTags(savedPeerId);
  }

  useEffect(() => {
    const scope = savedPeerId;
    loadSavedTags(scope).then((items) => {
      if(scope === currentSavedPeerId.current) tags.value = items;
    });
  }, [savedPeerId]);

  function startRename(tag: SavedTagItem) {
    renaming.value = tag.emoticon;
    renameValue.value = tag.title;
  }

  async function commitRename() {
    const emoticon = renaming.value;
    if(!emoticon) return;
    renaming.value = null;
    error.value = '';
    try {
      await renameSavedTag(emoticon, renameValue.value.trim());
      await refresh();
    } catch (err: any) {
      error.value = err?.type || err?.message || 'Could not rename the tag';
    }
  }

  // The whole strip — tags, the rename row and the error — is behind the
  // original's `{#if tags.length}`.
  if(!tags.value.length) return null;

  return (
    <>
      <div class="tags">
        <button
          class={['tag', !active && 'on'].filter(Boolean).join(' ')}
          onClick={() => onselect('')}
        >
          All
        </button>
        {tags.value.map((tag) => (
          <button
            key={tag.emoticon}
            class={['tag', tag.emoticon === active && 'on'].filter(Boolean).join(' ')}
            onClick={() => onselect(tag.emoticon === active ? '' : tag.emoticon)}
            onDblClick={() => startRename(tag)}
            title="Double-click to rename"
          >
            <span class="emoji">{tag.emoticon}</span>
            {tag.title && <span class="name">{tag.title}</span>}
            {tag.count > 0 && <span class="count">{tag.count}</span>}
          </button>
        ))}
      </div>

      {renaming.value && (
        <div class="rename">
          <input
            value={renameValue.value}
            placeholder="Tag name"
            maxlength={12}
            onInput={(e) => (renameValue.value = (e.target as HTMLInputElement).value)}
            onKeyDown={(e: KeyboardEvent) => {
              if(e.key === 'Enter') commitRename();
              else if(e.key === 'Escape') renaming.value = null;
            }}
          />
          <button onClick={commitRename}>Save</button>
          <button onClick={() => (renaming.value = null)}>Cancel</button>
        </div>
      )}

      {error.value && <p class="error">{error.value}</p>}
    </>
  );
}

// svelte/src/lib/components/SavedTags.svelte
<script lang="ts">
  import {loadSavedTags, renameSavedTag, type SavedTagItem} from '$lib/telegram/topics';

  let {
    savedPeerId,
    active = '',
    onselect
  }: {
    /** Scopes the tag list to one saved sub-chat; undefined means all of Saved. */
    savedPeerId?: number;
    active?: string;
    onselect: (emoticon: string) => void;
  } = $props();

  let tags = $state<SavedTagItem[]>([]);
  let renaming = $state<string | null>(null);
  let renameValue = $state('');
  let error = $state('');

  async function refresh() {
    tags = await loadSavedTags(savedPeerId);
  }

  $effect(() => {
    const scope = savedPeerId;
    loadSavedTags(scope).then((items) => {
      if (scope === savedPeerId) tags = items;
    });
  });

  function startRename(tag: SavedTagItem) {
    renaming = tag.emoticon;
    renameValue = tag.title;
  }

  async function commitRename() {
    const emoticon = renaming;
    if (!emoticon) return;
    renaming = null;
    error = '';
    try {
      await renameSavedTag(emoticon, renameValue.trim());
      await refresh();
    } catch (err: any) {
      error = err?.type || err?.message || 'Could not rename the tag';
    }
  }
</script>

{#if tags.length}
  <div class="tags">
    <button class="tag" class:on={!active} onclick={() => onselect('')}>All</button>
    {#each tags as tag (tag.emoticon)}
      <button
        class="tag"
        class:on={tag.emoticon === active}
        onclick={() => onselect(tag.emoticon === active ? '' : tag.emoticon)}
        ondblclick={() => startRename(tag)}
        title="Double-click to rename"
      >
        <span class="emoji">{tag.emoticon}</span>
        {#if tag.title}<span class="name">{tag.title}</span>{/if}
        {#if tag.count}<span class="count">{tag.count}</span>{/if}
      </button>
    {/each}
  </div>

  {#if renaming}
    <div class="rename">
      <input
        bind:value={renameValue}
        placeholder="Tag name"
        maxlength="12"
        onkeydown={(e) => {
          if (e.key === 'Enter') commitRename();
          else if (e.key === 'Escape') renaming = null;
        }}
      />
      <button onclick={commitRename}>Save</button>
      <button onclick={() => (renaming = null)}>Cancel</button>
    </div>
  {/if}

  {#if error}<p class="error">{error}</p>{/if}
{/if}

<style>
  .tags {
    display: flex;
    gap: 6px;
    align-items: center;
    overflow-x: auto;
    padding: 6px 10px;
    border-bottom: 1px solid var(--border);
  }

  .tag {
    display: flex;
    align-items: center;
    gap: 4px;
    flex: none;
    padding: 4px 10px;
    border: 1px solid var(--border);
    border-radius: 999px;
    background: transparent;
    color: inherit;
    font-size: 13px;
    cursor: pointer;
  }

  .tag.on {
    background: var(--accent);
    border-color: transparent;
    color: #fff;
  }

  .count {
    opacity: 0.7;
    font-size: 12px;
  }

  .rename {
    display: flex;
    gap: 6px;
    padding: 6px 10px;
    border-bottom: 1px solid var(--border);
  }

  .rename input {
    flex: 1;
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: transparent;
    color: var(--text);
    outline: none;
  }

  .rename button {
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: transparent;
    color: inherit;
    cursor: pointer;
  }

  .error {
    margin: 0;
    padding: 4px 10px;
    color: var(--danger);
    font-size: 13px;
  }
</style>
