// astro/src/components/SendAsPicker.tsx
/*
 * Ported from svelte/src/lib/components/SendAsPicker.svelte.
 *
 * Both effects read props only — the peer the picker was opened for, and the
 * `onclose` handler — so they are `useEffect`s with those in their dependency
 * lists (`useSignalEffect` tracks signal reads only). The second one is the
 * port of the `<svelte:window onkeydown>` binding: it adds and removes the same
 * listener, so Escape still closes the popover and nothing is left behind.
 */
import {useEffect} from 'preact/hooks';
import {useSignal} from '@preact/signals';

import {Avatar} from './Avatar';
import {loadSendAsOptions, saveSendAs, type SendAsOption} from '$lib/telegram/sendOptions';

import './SendAsPicker.css';

interface Props {
  peerId: number;
  /** Peer we currently post as, null when posting as ourselves. */
  current?: number | null;
  onpick: (sendAsPeerId: number) => void;
  onclose: () => void;
}

export function SendAsPicker({peerId, current = null, onpick, onclose}: Props) {
  const options = useSignal<SendAsOption[]>([]);
  const loading = useSignal(true);

  // The list is only fetched when the picker opens: channels.getSendAs is a
  // real round trip and must never sit on the chat-open path.
  useEffect(() => {
    const active = peerId;
    let cancelled = false;

    loadSendAsOptions(active)
    .then((list) => {
      if(cancelled) return;
      options.value = list;
      loading.value = false;
    })
    .catch(() => {
      if(cancelled) return;
      loading.value = false;
    });

    return () => {
      cancelled = true;
    };
  }, [peerId]);

  function pick(option: SendAsOption) {
    onpick(option.peerId);
    saveSendAs(peerId, option.peerId).catch(() => {});
    onclose();
  }

  function onKey(e: KeyboardEvent) {
    if(e.key === 'Escape') onclose();
  }

  useEffect(() => {
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onclose]);

  return (
    <div class="send-as-popover">
      <span class="head">Send message as…</span>

      {loading.value ?
        <p class="muted">Loading…</p> :
        !options.value.length ?
          <p class="muted">No other identity available.</p> :
          options.value.map((option) => (
            <button
              type="button"
              class={['option', option.peerId === current && 'on'].filter(Boolean).join(' ')}
              key={option.peerId}
              onClick={() => pick(option)}
              disabled={option.premiumRequired}
              title={option.premiumRequired ? 'Requires Telegram Premium' : option.title}
            >
              <Avatar peerId={option.peerId} title={option.title} size={28} />
              <span class="title">{option.title}</span>
            </button>
          ))}
    </div>
  );
}

// svelte/src/lib/components/SendAsPicker.svelte
<script lang="ts">
  import Avatar from './Avatar.svelte';
  import {loadSendAsOptions, saveSendAs, type SendAsOption} from '$lib/telegram/sendOptions';

  let {
    peerId,
    current = null,
    onpick,
    onclose
  }: {
    peerId: number;
    /** Peer we currently post as, null when posting as ourselves. */
    current?: number | null;
    onpick: (sendAsPeerId: number) => void;
    onclose: () => void;
  } = $props();

  let options = $state<SendAsOption[]>([]);
  let loading = $state(true);

  // The list is only fetched when the picker opens: channels.getSendAs is a
  // real round trip and must never sit on the chat-open path.
  $effect(() => {
    const active = peerId;
    let cancelled = false;

    loadSendAsOptions(active)
    .then((list) => {
      if (cancelled) return;
      options = list;
      loading = false;
    })
    .catch(() => {
      if (cancelled) return;
      loading = false;
    });

    return () => {
      cancelled = true;
    };
  });

  function pick(option: SendAsOption) {
    onpick(option.peerId);
    saveSendAs(peerId, option.peerId).catch(() => {});
    onclose();
  }

  function onKey(e: KeyboardEvent) {
    if (e.key === 'Escape') onclose();
  }
</script>

<svelte:window onkeydown={onKey} />

<div class="send-as-popover">
  <span class="head">Send message as…</span>

  {#if loading}
    <p class="muted">Loading…</p>
  {:else if !options.length}
    <p class="muted">No other identity available.</p>
  {:else}
    {#each options as option (option.peerId)}
      <button
        type="button"
        class="option"
        class:on={option.peerId === current}
        onclick={() => pick(option)}
        disabled={option.premiumRequired}
        title={option.premiumRequired ? 'Requires Telegram Premium' : option.title}
      >
        <Avatar peerId={option.peerId} title={option.title} size={28} />
        <span class="title">{option.title}</span>
      </button>
    {/each}
  {/if}
</div>

<style>
  .send-as-popover {
    position: absolute;
    left: 8px;
    bottom: calc(100% + 8px);
    width: min(260px, calc(100vw - 32px));
    max-height: 260px;
    overflow-y: auto;
    display: grid;
    gap: 2px;
    padding: 8px;
    background: var(--bg-solid, var(--bg-elevated));
    border: 1px solid var(--border);
    border-radius: 12px;
    z-index: 40;
  }

  .head {
    font-size: 11px;
    color: var(--text-dim);
    padding: 2px 4px 6px;
  }

  .muted {
    margin: 0;
    padding: 0 4px 4px;
    font-size: 12px;
    color: var(--text-dim);
  }

  .option {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px;
    border: none;
    border-radius: 8px;
    background: transparent;
    color: inherit;
    font-size: 13px;
    text-align: left;
    cursor: pointer;
  }

  .option:hover {
    background: color-mix(in srgb, var(--text) 8%, transparent);
  }

  .option.on {
    background: color-mix(in srgb, var(--accent) 18%, transparent);
  }

  .option:disabled {
    opacity: 0.45;
    cursor: default;
  }

  .title {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>
